### ISSUE TITLE
Fix pixel-thin line between videos

### ISSUE THREAD

**Issue by ariel** [basilleaf/luti#43]
In some parts of the grid, I can see a pixel-thin line between some (but not all) of the videos. Need to make sure that all videos are either perfectly aligned, or slightly overlapped.

**Comment by basilleaf** [comment]
I saw this in the prototype, a couple of thoughts: make sure we are using the correct background on the html document might fix this, I think you made a little slice at some point for us to tile? 

if that doesn't work another way to fix this is to make each map overlay coordinates be a few pixels smaller than the actual video size, this is what I had in the prototype and it seemed to do the trick.. so that was like adding 5 pixels to each overalay's lower left x,y coordinates and subtract the same from the upper left x,y, so that all the videos are all overlapping each other a bit

**Comment by ariel** [comment]
Cc-ing Matt

**Comment by mattb** [comment]
Fixed in 5c6dc9030ceec926021ce1d278a4983580409933
